#!/usr/bin/env bash

shopt -s nullglob

# Configuration
_repo=${ELLIPSIS_REPO:-$HOME/.ellipsis}
_target=${ELLIPSIS_TARGET:-$HOME}

main() {
	showUsage() {
		cat <<- 'EOF'
		Usage: ellipsis <command>

		An interactive dotfile manager using GNU Stow

		<command>
		  init - Initialize ellipsis repository/environment
		  pkg  - Manages the packages in the ellipsis repository
		  env  - Manages the packages/files in the ellipsis environment
		  git  - Run git commands within the ellipsis repository
		EOF
	}

	# Parse global options
	while getopts 'h' flag; do
		case "$flag" in
			'h')
				showUsage
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

	# Capture the verb
	_command=$1
	shift

	case "$_command" in
		'init')
			verb_init "$@"
			;;
		'pkg')
			verb_pkg "$@"
			;;
		'env')
			verb_env "$@"
			;;
		'git')
			verb_git "$@"
			;;
		'')
			echo 'No command specified'
			showUsage
			exit  1
			;;
		*)
			echo "Unknown command: $_command"
			showUsage
			exit 1
			;;
	esac
}

########
# INIT #
########

verb_init() {
	showUsage() {
		cat <<- EOF
		Usage: ellipsis init [-r git_repo]

		Inializes ellipsis on the current machine, if it is not currently
		configured.

		OPTIONS
		  -r - The URL of the git repository from which to initialize the
		       ellipsis repo.
		EOF
	}

	# Parse additional options
	while getopts 'rh' flag; do
		case "$flag" in
			'r')
				_git_repo="$2"
				shift
				;;
			'h')
				showUsage
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

	# Check if ellipsis is already installed
	if [[ -e "$_repo" ]]; then
		debug "Ellipsis appears to already be initialized on this machine; $_repo is populated"
		exit 1
	fi

	# Initialize from git repo if specified
	if [[ -n "$_git_repo" ]]; then
		if [[ "$_git_repo" =~ ^[a-zA-Z0-9]{1,}/[a-zA-Z0-9]{1,}$ ]]; then
			if command -v gh &>/dev/null && confirm "Initialize ellipsis repo at $_repo using 'gh repo clone $_git_repo'?"; then
				gh repo clone "$_git_repo" "$_target"
				return $?
			fi

			# Normalize the URL for cloning with 'git'
			_git_repo="https://github.com/$_git_repo" 
		fi

		if ! command -v git &>/dev/null; then
			debug "You must have 'git' installed to clone a git repository"
			exit 1
		fi

		# Clone with git if available
		if confirm "Initialize ellipsis repo at $_repo using 'git clone $_git_repo'?"; then
			git clone "$_git_repo" "$_target"
			return $?
		else
			return 1
		fi
	fi

	# Initialize directories on machine
	if confirm "Initialize ellipsis using $_repo"; then
		mkdir -p "$_repo"
		return $?
	else
		exit 1
	fi
}

#######
# PKG #
#######

verb_pkg() {
	showUsage() {
		cat <<-EOF
		Usage: ellipsis pkg <command>

		<command>
		  mk - Create a new package
		  ls - List packages managed by ellipsis
		  mv - Rename an existing package
		  rm - Delete an existing package
		EOF
	}

	# Parse additional options
	while getopts 'h' flag; do
		case $flag in
			'h')
				showUsage
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

	local _command=$1
	shift

	case "$_command" in
		'mk')
			verb_pkg_mk "$@"
			;;
		'ls')
			verb_pkg_ls "$@"
			;;
		'mv')
			verb_pkg_mv "$@"
			;;
		'rm')
			verb_pkg_rm "$@"
			;;
	esac
}

##########
# PKG MK #
##########

verb_pkg_mk() {
	showUsage() {
		cat <<- 'EOF'
		Usage: ellipsis pkg mk <package>

		Creates a new package to be managed by ellipsis

		<package> - The name of the package to create
		EOF
	}

	while getopts 'h' flag; do
		case "$flag" in
			'h')
				showUsage
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

	# Validate that package(s) was specified
	if [[ -z "$*" ]]; then
		debug "No package(s) specified"
		showUsage
		exit 1
	fi

	for package in "$@"; do
		mkdir -p "$_repo/$package"
	done
}

##########
# PKG LS #
##########

verb_pkg_ls() {
	showUsage() {
		cat <<- EOF
		Usage: ellipsis pkg ls [-i | -u]

		Lists all packages that are managed by ellipsis

		OPTIONS
		  -i - Only list the installed packages
		  -u - Only list uninstalled packages
		EOF
	}

	while getopts 'iuh' flag; do
		case $flag in
			'i')
				_flag_i=1
				;;
			'u')
				_flag_u=1
				;;
			'h')
				showUsage
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

	if [[ $_flag_i -eq 1 ]]; then
		lsInstalledPackages
	elif [[ $_flag_u -eq 1 ]]; then
		comm -23 <(lsAllPackages) <(lsInstalledPackages)
	else
		lsAllPackages
	fi
}

lsAllPackages() {
	for package in "$_repo"/*; do
		realpath --relative-to "$_repo" "$package"
	done
}

lsInstalledPackages() {
	find "$_target"/.* -maxdepth 5 -type l -print0 \
		| xargs -0 realpath 2>/dev/null \
		| grep -E "^$_repo" \
		| xargs realpath --relative-to "$_repo" \
		| cut -d / -f1 \
		| sort -u 
}

##########
# PKG MV #
##########

verb_pkg_mv() {
	showUsage() {
		cat <<- 'EOF'
		Usage: ellipsis pkg mv <package> <name>

		<package> - The package to rename
		<name>    - The new name of the package
		EOF
	}

	while getopts 'h' flag; do
		case $flag in
			'h')
				showUsage
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

}

##########
# PKG RM #
##########

verb_pkg_rm() {
	showUsage() {
		cat <<-'EOF'
		Usage: ellipsis pkg rm [<package...>]
		EOF
	}

	while getopts 'h' flag; do
		case "$flag" in
			'h')
				showUsage
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

	local packages="$*"

	# If no package is specified, prompt the user to pick one
	if [[ -z "$packages" ]]; then
		if ! packages=$(lsAllPackages | pick); then
			debug "No package specified"
			exit 1
		fi
	fi

	for package in $packages; do
		if confirm "Delete and uninstall $package"; then
			verb_env_rm "$package"
			rm -r "${_repo:?}/$package"
		else
			debug "Cancelled deletion"
		fi
	done
}

#######
# ENV #
#######

verb_env() {
	showUsage() {
		cat <<- 'EOF'
		Usage: ellipsis env <command>

		<command>
		  add     - Add a package to the environment
		  rm      - Remove a package from the environment
		  pack    - Add a file in the env to a package
		  unpack  - Remove a file in the env from its package
		EOF
	}

	while getopts 'h' flag; do
		case "$flag" in
			'h')
				showUsage
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

	local _command="$1"
	shift

	case "$_command" in
		'add')
			verb_env_add "$@"
			;;
		'rm')
			verb_env_rm "$@"
			;;
		'import'|'in'|'adopt'|'pack')
			verb_env_pack "$@"
			;;
		'export'|'out'|'disown'|'unpack')
			verb_env_unpack "$@"
			;;
		*)
			debug "Unknown command: $_command"
			showUsage
			exit 1
			;;
	esac
}

###########
# ENV ADD #
###########

verb_env_add() {
	showUsage() {
		cat <<- 'EOF'
		Usage: ellipsis env add [<package>...]

		Add a package to the user's environment

		package - The package which should be installed. If none is specified,
		an interactive picker will be presented to the user.
		EOF
	}

	while getopts 'h' flag; do
		case "$flag" in
			'h')
				showUsage
				exit 0
				;;
			'?')
				showUsage
				exit 0
				;;
		esac
	done

	local packages="$*"

	# If no package is specified, prompt the user to pick one
	if [[ -z "$packages" ]]; then
		if ! packages=$(lsAllPackages | pick); then
			debug "No package specified"
			exit 1
		fi
	fi

	for package in $packages; do
		stow "$package"
	done
}

##########
# ENV RM #
##########

verb_env_rm() {
	showUsage() {
		cat <<-'EOF'
		Usage: ellipsis env rm <package...>

		Uninstall a package from the environment

		<package...> - The package(s) to uninstall from the environment
		EOF
	}

	while getopts 'h' flag; do
		case "$flag" in
			'h')
				showUsage
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

	local packages="$*"

	# If no package is specified, prompt the user to pick one
	if [[ -z "$packages" ]]; then
		if ! packages=$(lsInstalledPackages | pick); then
			debug "No package specified"
			exit 1
		fi
	fi

	for package in $packages; do
		stow --delete "$package"
	done
}

############
# ENV PACK #
############

verb_env_pack() {
	showUsage() {
		cat <<- 'EOF'
		Usage: ellipsis env pack [-p <package>] <file> [<file>...]

		Specifies a file/directory to begin managing in an ellipsis package

		file - The file(s) that the user wants to begin managing using ellipsis

		OPTIONS
		  -p <package> - Specifies the file(s) should be added to <package>. If
		  unspecified, an interactive picker will be presented to the user.
		EOF
	}

	local package
	while getopts 'ph' flag; do
		case "$flag" in
			'p')
				package="$2"
				shift 2
				;;
			'h')
				showUsage 
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

	if [[ "$*" == "" ]]; then
		debug "No file(s) to pack were specified"
		exit 1
	fi

	# If no package has been specified, prompt the user for one.
	if [[ -z "$package" ]]; then
		if ! package="$(lsAllPackages | pick)"; then
			debug "No package was specified"
			exit 1
		fi
	fi

	# Adopt the files into the specified package
	for file in "$@"; do
		_dst="$_repo/$package/$(realpath --relative-to "$_target" "$file")"

		mkdir -p "$(dirname "$_dst")"
		mv "$file" "$_dst"
		ln -s "$(realpath  --relative-to "$(dirname "$file")" "$_dst")" "$file"
	done
}

##############
# ENV UNPACK #
##############

verb_env_unpack() {
	showUsage() {
		cat <<- 'EOF'
		Usage: ellipsis env unpack <file> [<file>...]

		Remove a file from its ellipsis repo/package, but keep it in the ellipsis target

		file - The file(s) to unpack from the ellipsis repository
		EOF
	}

	while getopts 'h' flag; do
		case "$flag" in
			'h')
				showUsage 
				exit 0
				;;
			'?')
				showUsage
				exit 1
				;;
		esac
	done

	# TODO: Use picker
	if [[ "$*" == "" ]]; then
		debug "No file(s) to unpack were specified"
		exit 1
	fi

	for file in "$@"; do
		# Confirm file is a symlink
		# TODO: Check if any parent is a symlink
		if [[ ! -L $file ]]; then
			debug "$file is not a symlink"
			continue
		fi

		# Confirm this symlink is managed by ellipsis
		_repo_file="$(realpath "$file")"
		if [[ ! $_repo_file == $_repo* ]]; then
			debug "$file is not managed by ellipsis"
			continue
		fi

		# Replace symlink with target file
		rm "$file" && mv "$_repo_file" "$file"
	done
}

#######
# GIT #
#######

verb_git() {
	if ! [[ -d "$_repo/.git" ]]; then
		printf "No git repository detected at %s\n" "$_repo/.git"
		exit 1
	fi

	exec git --git-dir="$_repo/.git" --work-tree="$_repo" "$@"
}

#########
# UTILS #
#########

confirm() {
	local prompt="$1"

	while true; do
		read -rp "$prompt (y/n): " answer
		case "$answer" in
			'y')
				return 0
				;;
			'n')
				return 1
				;;
		esac
	done
}

pick() {
	if command -v fzf &>/dev/null; then
		fzf
	else
		debug "No supported picker (e.g. fzf) is installed"
		return 1
	fi
}

fail() {
	echo "$@" >&2
	exit 1
}

debug() {
	echo "$@" >&2
}

stow() {
	command stow --dir "$_repo" --target "$_target" "$@"
}

main "$@"

